#pragma once

#include <Arduino.h>

/* Main constants */
#define PRO_CORE_ID 0
#define APP_CORE_ID 1

#define CAN_RX_TASK_PRIORITY 5
#define CAN_PROCESSING_TASK_PRIORITY 4
#define ELM327_TASK_PRIORITY 1

/* PIDController constants */
#define PID_KP 0.12f
#define PID_KI 0.002f
#define PID_KD 0.8f
#define MAIN_LOOP_PERIOD_MS 50
#define THROTTLE_RATE_UP_PER_SEC 15.0f
#define THROTTLE_RATE_DOWN_PER_SEC 40.0f
#define THROTTLE_MAX_DELTA_UP (THROTTLE_RATE_UP_PER_SEC * (MAIN_LOOP_PERIOD_MS / 1000.0f))
#define THROTTLE_MAX_DELTA_DOWN (THROTTLE_RATE_DOWN_PER_SEC * (MAIN_LOOP_PERIOD_MS / 1000.0f))

/* Indicator LED constants */
#define INDICATOR_LED_PIN GPIO_NUM_25
#define INDICATOR_LED_PWM_CHANNEL 0
#define INDICATOR_LED_PWM_FREQ_HZ 1000
#define INDICATOR_LED_PWM_RESOLUTION_BITS 8
#define INDICATOR_LED_PWM_RESOLUTION (1<<INDICATOR_LED_PWM_RESOLUTION_BITS)
#define INDICATOR_LED_PWM_MAX (INDICATOR_LED_PWM_RESOLUTION-1)

/* Throttle constants */
#define THROTTLE_APPS1_PIN GPIO_NUM_23
#define THROTTLE_APPS2_PIN GPIO_NUM_22
#define THROTTLE_APPS1_PWM_CHANNEL 2
#define THROTTLE_APPS2_PWM_CHANNEL 3
#define THROTTLE_PWM_FREQ_HZ 19000
#define THROTTLE_PWM_RESOLUTION_BITS 12
#define THROTTLE_PWM_RESOLUTION (1<<THROTTLE_PWM_RESOLUTION_BITS)
#define THROTTLE_PWM_MAX (THROTTLE_PWM_RESOLUTION-1)

#define THROTTLE_APPS2_PEDAL_PIN GPIO_NUM_34

#define THROTTLE_RELAY_PIN GPIO_NUM_19

/* Brake / Clutch constants */
#define BRAKE_CLUTCH_PIN GPIO_NUM_18

/* Buttons constants */
#define BUTTONS_PIN GPIO_NUM_35

/* CAN bus constants */
#define CAN_TX_GPIO GPIO_NUM_5
#define CAN_RX_GPIO GPIO_NUM_4
#define CAN_SPEED TWAI_TIMING_CONFIG_500KBITS()
#define CAN_SLEEP_TIME_MS 100
#define CAN_RX_QUEUE_LENGTH 16
#define CAN_PROCESSING_QUEUE_LENGTH 100
#define SNAPSHOT_PERIOD_MS 20

/* ELM327 constants */
#define USE_SERIAL2
#ifdef USE_SERIAL2
    #define ELM327_SERIAL Serial2
    #define ELM327_SERIAL_RX_PIN GPIO_NUM_16
    #define ELM327_SERIAL_TX_PIN GPIO_NUM_17
#else
    #define ELM327_SERIAL Serial
#endif
#define ELM327_SERIAL_BAUDRATE 115200
