#pragma once

#include <Arduino.h>

/* Main constants */
#define PRO_CORE_ID 0
#define APP_CORE_ID 1

#define CAN_RX_TASK_PRIORITY 5
#define CAN_PROCESSING_TASK_PRIORITY 4
#define ELM327_TASK_PRIORITY 1

/* Indicator LED constants */
#define INDICATOR_LED_PIN GPIO_NUM_25
#define INDICATOR_LED_PWM_CHANNEL 0
#define INDICATOR_LED_PWM_FREQ_HZ 1000
#define INDICATOR_LED_PWM_RESOLUTION_BITS 8
#define INDICATOR_LED_PWM_RESOLUTION (1<<INDICATOR_LED_PWM_RESOLUTION_BITS)
#define INDICATOR_LED_PWM_MAX (INDICATOR_LED_PWM_RESOLUTION-1)

/* CAN bus constants */
#define CAN_TX_GPIO GPIO_NUM_5
#define CAN_RX_GPIO GPIO_NUM_4
#define CAN_SPEED TWAI_TIMING_CONFIG_500KBITS()
#define CAN_SLEEP_TIME_MS 100
#define CAN_RX_QUEUE_LENGTH 16
#define CAN_PROCESSING_QUEUE_LENGTH 100
#define SNAPSHOT_PERIOD_MS 20

/* ELM327 constants */
#define USE_SERIAL2
#ifdef USE_SERIAL2
    #define ELM327_SERIAL Serial2
    #define ELM327_SERIAL_RX_PIN GPIO_NUM_16
    #define ELM327_SERIAL_TX_PIN GPIO_NUM_17
#else
    #define ELM327_SERIAL Serial
#endif
#define ELM327_SERIAL_BAUDRATE 115200
